<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>JS错误处理</title>
</head>

<body>
    <script>
        /**
         * 语法固定 try...catch   try 尝试的意思  catch 捕获
         * 1. try catch捕获到错误之后, 后续代码可以继续执行
         * 2. catch 可以将错误信息捕获到. e 是一个对象, 有message和stack两个属性
         * 3. 抛出错误之后, 在后续的 try 里面的代码不会执行
         * 4. try 不能捕获语法错误. 其他三种类型错误可以捕获.
         * 5. 允许使用 throw 手动的抛出错误
         * 6. 抛出任意类型的数据
         */

        try{
            //这里正常编写逻辑代码
            let num = 100;
            let n = 0;
            // let result = num * n;
            if(n === 0){
                //throw 抛  
                // throw new Error('除数不能为 0');
                throw '出错啦!!';
            }
            let result = num / n;
            console.log("hello");
        }catch(e){
            //这里处理产生的错误
            console.dir(e);
        }

        console.log('继续执行');
    </script>
</body>

</html>